# Generated by Django 4.1.7 on 2023-03-25 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portal",
            name="description",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portal",
            name="name",
            field=models.CharField(default=2, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
